id: I6A606A54
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T17:36:31+00:00'
last_modified: '2022-06-08T17:06:23.775789+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03598
  title: ཁྲི་ཆེན་རབ་བརྟན་རྒྱ་མཚོའི་རྣམ་ཐར་རྒྱས་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5A86:
      image_group_id: I00KG03616
      title: ''
      total_pages: 105
      order: 1
      base_file: 5A86.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
